image: ubuntu:xenial
before_script:
- apt-get update -qyy
- apt-get install -qyy curl bc make git build-essential
- apt-get install libncurses5-dev
- apt-get install git-core gnupg flex bison gperf build-essential zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386

building:
script:
 - git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
 - export PATH=$PATH:$PWD/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin/
- export KBUILD_BUILD_USER=KI.LAB
- export KBUILD_BUILD_HOST=ZenProject
- export ARCH=arm64
- export SUBARCH=arm64
- export CROSS_COMPILE=$PWD/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin/aarch64-linux-android---
- make -j16 ze500kg-custom_defconfig
- make -j16 1>builds.log 2>errors.log 
after_script:
- curl --upload-file builds.log https://transfer.sh/builds.log |grep transfer
- curl --upload-file errors.log https://transfer.sh/errors.log |grep transfer
- curl --upload-file arch/arm/boot/zImage-dtb https://transfer.sh/zImage-dtb |grep transfer
